#!/bin/bash

function get_abs_path() {
    readlink -f $1 
}

SELF_PATH=$(dirname $(get_abs_path $(which $0)))

cd ~/bin
ln -fs $SELF_PATH/apktool
ln -fs $SELF_PATH/baksmali
ln -fs $SELF_PATH/smali
ln -fs $SELF_PATH/baksmali.jar
ln -fs $SELF_PATH/smali.jar
ln -fs $SELF_PATH/vdexExtractor
ln -fs $SELF_PATH/jadx-dir/bin/jadx
ln -fs $SELF_PATH/jadx-dir/bin/jadx-gui
ln -fs $SELF_PATH/compact_dex_converter compact_dex_converter

case $(uname -s) in
    Linux)
        ln -fs $SELF_PATH/dextra.ELF64 dextra
        ;;
    Darwin)
        ln -fs $SELF_PATH/dextra dextra
        ;;
esac
